print("Intresting Psychology Facts")
print("Human attention span is shorter than a fish's attention span")
print("The human brain uses 20% of a person's energy")
print("Eating bananas can actually uplift a person's mood")
print("When a person dies, their brain replays that person's favorite memories for 7 minutes")
print("Happy people don't need as much sleep and sad people do")

print("But what really is Psychology and what are the types?")
print("Psychology is the scientific study of the human mind and how it reacts and behaves")
print("The many different types of Psychology include, Biopsychology, counselling Psychology, Developmental Psychology, Educational Psychology, and many more")
print("Biopsychology focuses on analyzing how the brain and behavior interact with biological processes")
print("counseling Psychology is like theraphy, helping people manage stress in their life")
print("Developemtal Psychology studies psychological growth")
print("Educational Psychology specifically focuses on how different people learn and how their brain retains information.")