print("Intresting Psychology Facts")
print("Human attention span is shorter than a fish's attention span")
print("The human brain uses 20% of a person's energy")
print("Eating bananas can actually uplift a person's mood")
print("When a person dies, their brain replays that person's favorite memories for 7 minutes")
print("Happy people don't need as much sleep and sad people do")

print("But what really is Psychology and what are the types?")
print("Psychology is the scientific study of the human mind and how it reacts and behaves")
print("The many different types of Psychology include, Biopsychology, counselling Psychology, Developmental Psychology, Educational Psychology, and many more")
print("Biopsychology focuses on analyzing how the brain and behavior interact with biological processes")
print("counseling Psychology is like theraphy, helping people manage stress in their life")
print("Developemtal Psychology studies psychological growth")
print("Educational Psychology specifically focuses on how different people learn and how their brain retains information.")

print("What are some carrers in Psychology?")
print("School counselor: they help with one's mental health, and education in school")
print("Therapist: they help treat someone's psychological challenges")
print("I-O psychologists: help with hiring process, see employee behavior, and boost productivity in a workplace")

print("Impact of social media on children")
print("Lack of confidence. Children often compare themselves with strangers online and loose more confidence.")
print("Anxiety. Children often get very anxious before and after social media.")
print("Eye stress. Hours of screen time can increase stress on eyes.")

print("Psychology of childhood trauma")
print("At a young age, kids who suffered childhood trauma eventually have a hard time accepting peace.")
print("They often feel like something bad will happen soon no matter how happy their life is going.")
print("They also have problems making friends due to the stress they faced so early on.")

print("Psychology of skin picking")
print("When someone skin-picks, it eventually turns into a coping habit.")
print("It turns into a coping mechinism because it feels like that is the only thing they can control in the moment of anxiety.")
print("Often time, the person skin picking or nail picking doesn't realize they are doing that until their skin bellds or it hurts.")

print("What is Dopamine?")
print("It is a harmone that makes you 'feel good' and keeps you motivated.")
print("This is why many people spend hours doom scrolling because dopamine gets released which keeps them stuck at a repeating cycle.")
print("Although domapine makes us feel good and motivated, excessive amount of it can be dangerous and it can become dangerous from drugs or schizophrenia.")

print("What is Serotonin?")
print("It is a chemical in the brain ment to stablize one's mood.")
print("Serotonin can be released while meditation, or talking a walk")
print("These activites are calming and makes one's mind step away from chos in their mind and release Serotonin.")

print("What is Oxytocin?")
print("Oxytocin is a happy harmone used to relieve stress and make bonds.")
print("One way to release Oxytocin is by showing kindness and volunteering.")
print("Oxytoxcin is also known to be released during brestfeeding and is also know as the 'love harmone'.")

print("Psychology of OCD")
print("If someone struggles with OCD, they may do things in a certain way to calm their anxiety down.")
print("They may be stuck in a loop of obeying their brain in order to survive or feel better.")
print("These tasks can feel threathing if not done so if you know someone struggling with this or if you are struggling, then please seek help from a trusted adult because you are not alone.")

